### ISSUE TITLE
[enhancement] utest-tiny (utest without scheduling)

### ISSUE THREAD

**Issue by PrzemekWirkus** [ARMmbed/utest#8]
# Description
Currently utest is using minar for test scheduling. We would like to keet ```Harness``` APIs but be able to run our test cases in as tiny as possible environment.
We would take advantage of things like:
* Harness / Cases / test case summary, reporting.
* Greentea handlers.

We would not need:
* Minar dependency (scheduling).

# Rationale
We want to wrap all test cases in test suites with utest APIs. Currently we will have to hack modules like e.g. ```minar``` and add testcase_start/finish messages manually.

**Comment by 0xc0170** [comment]
+1 for this to support. I was actually thinking to have this for mbed-hal tests

**Comment by bridadan** [comment]
+1 from me as well. But what would that imply for the current implementation? Implement a basic callback queue?

**Comment by niklas-arm** [comment]
Since the harness only uses a very small subset of minar (ie. x ms callbacks without bindings and callback cancellation) the way I'd approach this is to provide a abstract scheduling class that needs to be implemented by the user.
This class would be defaulted to a minar implementation, but can be overwritten on demand.

This means for testing HAL component, you have to implement certain functionality manually or ignore it.
So for example when you're testing the LP ticker, which minar uses to schedule, you need to implement the scheduler use another timer, or not use the async functionality of `utest`.

This needs to be well documented though, since this smells a lot like a plug-in API.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2120

**Comment by bogdanm** [comment]
> Since the harness only uses a very small subset of minar (ie. x ms callbacks without bindings and callback cancellation) the way I'd approach this is to provide a abstract scheduling class that needs to be implemented by the user.

*IF* that's really really needed, the only sane solution I see to this is that the scheduling class needs to be implemented in terms of our own HAL (for example using LP ticker like MINAR). But then of course we won't be able to test the LP ticker with utest (which might be a limitation that we just need to live with).

**Comment by niklas-arm** [comment]
I have added a [scheduler interface](https://github.com/ARMmbed/utest/commit/4736adff073c632a4f2c02a69382c72c21300b5e).
It allows a custom scheduler implementation which [for example uses `us_ticker`](https://github.com/ARMmbed/utest/commit/06ab2165e3a79879933f71f698e13bd1213d50d4).
